version: "3.6"

services:
  ch-sub-1:
    container_name: ch-sub-1
    image: yandex/clickhouse-server
    ports:
      - 92:9000
      - 82:8123
    volumes:
      - type: volume
        source: ch-sub-1-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-sub-1-logs
        target: /var/log/clickhouse-server
      - ./config/sub-1-config.xml:/etc/clickhouse-server/config.xml
  zk-2:
    container_name: zk-2
    hostname: zk-2
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zk1:2888:3888

volumes:
  ch-sub-1-data:
  ch-sub-1-logs:


